### ISSUE TITLE
Integrate an LMS such as Moodle

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/offlinewebinfra#11]
_From @intelliant01 on May 25, 2017 18:12_

An LMS such as Moodle will be of great utility to the users of the MSS, expecially for those who want to use this as a custom weaved educational content platform or as an online evaluation tool for computer or even other subjects.
There has been a request for the same from multiple sources.

_Copied from original issue: RechercheTech/mss#39_

**Comment by intelliant01** [comment]
_From @cyberorg on May 26, 2017 4:0_

Assign to me when you have the bundle ready for deployment.

**Comment by intelliant01** [comment]
@cyberorg 

**Recommended** - Rename existing offlineweb mss folder to mss.backup. Clone repo from https://github.com/RechercheTech/offlinewebinfra

```git clone git@github.com:RechercheTech/offlinewebinfra.git mss```

and move in third-party content in the respective folders from mss.backup and continue.

1. sudo apt install unoconv - needed for a document converter plugin of moodle.

2. Download the customized moodle archive from the link below and uncompress it at /var/www/html/mss/

https://drive.google.com/file/d/0B2wpK6fFQqSjVTNmR0VHczRDQlk/view?usp=sharing

We should have a moodle folder under mss now.

3. Add this to /etc/rc.local -

```/var/www/html/mss/moodle/ctlscript.sh start 2>/dev/null || true```

4. Create /var/www/html/mss/indexer/htmls/40-moodle.html with the following content (not needed if offlinewebinfra repo has been cloned) -
```
                        <div class="post-masonry col-md-4 col-sm-6">
                            <div class="post-thumb">
                                <img src="moodle.png" alt="">
                                <div class="title-over">
                                    <h4><a href="#">Robust learning environment</a></h4>
                                </div>
                                <div class="post-hover text-center">
                                    <div class="inside">
                                        <h4><a href="http://server:81/"><i class="fa fa-plus"></i>Customisable learning environment</h4></a><br>
                                        <p>Powered by Moodle</p></a>
                                        <a href="https://moodle.org/">moodle.org</a>
                                    </div>
                                </div>
                            </div>
                        </div><!-- /.post-masonry -->
```
5. Regenerate index.html (not needed if offlinewebinfra repo has been cloned)

6. Restart MSS and moodle should be available at http://server:81

**Comment by intelliant01** [comment]
@cyberorg Where should I place the uncompressed moodle archive on the install server for faster sync when you are ready?

**Comment by cyberorg** [comment]
/home/mss

**Comment by cyberorg** [comment]
mssupdate serverip moodle

**Comment by intelliant01** [comment]
@cyberorg Missed an important step that needs to be included at the end of the moodle deployment process - ```usermod -a daemon -G shadow```
