### ISSUE TITLE
kalite does not work as expected after restructuring

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/offlinewebinfra#13]
kalite is not working as expected after the restructuring done at 08ca6345cb5048bf8e12f83ff6a6b43c8c0b151f .

![kalite-not-starting](https://user-images.githubusercontent.com/2577060/27537250-a0d0face-5a90-11e7-9977-750121049612.png)

syslog : 

```
Jun 26 16:46:05 server systemd[1]: Stopping LSB: ka-lite daemon, a local Khan Academy content server...
Jun 26 16:46:05 server systemd[1]: Started Session c14 of user mssadmin.
Jun 26 16:46:06 server ka-lite[6822]: kalite stopped
Jun 26 16:46:06 server systemd[1]: Stopped LSB: ka-lite daemon, a local Khan Academy content server.
Jun 26 16:46:06 server systemd[1]: Starting LSB: ka-lite daemon, a local Khan Academy content server...
Jun 26 16:46:06 server systemd[1]: Started Session c15 of user mssadmin.
Jun 26 16:46:06 server ka-lite[6840]: Running 'kalite start' as daemon (system service)
Jun 26 16:46:06 server ka-lite[6840]: Stand by while the server loads its data...
Jun 26 16:46:06 server ka-lite[6840]: Going to daemon mode, logging to /home/mssadmin/.kalite/server.log
Jun 26 16:46:07 server systemd[1]: Started LSB: ka-lite daemon, a local Khan Academy content server.

```

/home/mssadmin/.kalite/server.log : 

```
[INFO] [2017-06-26 16:46:07,848] cherrypy.error: [26/Jun/2017:16:46:07] ENGINE Listening for SIGHUP.
[INFO] [2017-06-26 16:46:07,848] cherrypy.error: [26/Jun/2017:16:46:07] ENGINE Listening for SIGTERM.
[INFO] [2017-06-26 16:46:07,849] cherrypy.error: [26/Jun/2017:16:46:07] ENGINE Listening for SIGUSR1.
[INFO] [2017-06-26 16:46:07,849] cherrypy.error: [26/Jun/2017:16:46:07] ENGINE Bus STARTING
[INFO] [2017-06-26 16:46:07,849] cherrypy.error: [26/Jun/2017:16:46:07]  Loading and serving the Django application
[INFO] [2017-06-26 16:46:07,861] cherrypy.error: [26/Jun/2017:16:46:07] ENGINE Started monitor thread '_TimeoutMonitor'.
[INFO] [2017-06-26 16:46:08,018] cherrypy.error: [26/Jun/2017:16:46:08] ENGINE Serving on http://0.0.0.0:8008
[INFO] [2017-06-26 16:46:08,020] cherrypy.error: [26/Jun/2017:16:46:08] ENGINE Bus STARTED
```

**Comment by cyberorg** [comment]
I cannot figure anything out from such huge commit, can you point me to changes which you think could have broken it?

**Comment by intelliant01** [comment]
I cleaned up mss/images folder and deleted one or more .backup files. Should not have impacted kalite in anyway as it is completely housed out of mss if I know it correct.

I suggest you checkout, put the appropriate content in the folders under mss and try for yourself. I don't think it is related to the cleanup and could be something external. If nothing else makes sense then will try with a kalite cleanup and reinstall on this device later today.

**Comment by intelliant01** [comment]
@cyberorg It doesn't seem to be related to restructuring. Did a rysnc from install server of the kalite content and it worked. 
Suspect something may have gone wrong during this specific instance installation or the install archive may be broken in some form. Will be confirmed once I do another installation once the install server is ready tomorrow.
