### ISSUE TITLE
Modularise loading of RACHEL content 

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/offlinewebinfra#3]
_From @intelliant01 on May 25, 2017 17:52_

For example, the wikipedia for schools integrated into RACHEL is not sufficient for most current project usage scenarios presented by teachers / assigned to students, such as when researching for "PM of India" or the "Ebola virus" and some other scenarios.
 
Hence we must only load whatever modules are most useful from the RACHEL repo - http://dev.worldpossible.org/cgi/rachelmods.pl

_Copied from original issue: RechercheTech/mss#37_

**Comment by intelliant01** [comment]
_From @cyberorg on May 26, 2017 4:18_

Only load whatever modules are most useful from the RACHEL repo requires "rachel server" which is different from static rachel usb we are using, there is no known deb packages for ubuntu available as of now so not possible to implement it. 

Edit mss/rachel/RACHEL/index.html and remove mss/rachel/RACHEL/modules/<module> as per requirement.

Use Xowa if the latest and complete wikipedia is required. To add/update use xowa interface.

cd /var/www/html/web/xowa
sudo ./xowa.sh

**Comment by intelliant01** [comment]
@cyberorg will close it when something sustainable and acceptable has been implemented. It is again about how the install server and the mss will require modifications for the same.

(Don't bother closing it  and others till the story's goal is achieved and I suggest that the status be determined by the story owner. And yes surely these may be moderated and closed if left dangling across some review period.)

**Comment by intelliant01** [comment]
_From @cyberorg on May 26, 2017 6:22_

Rachel server has the modular installation, MSS will not be integrating that so don't see any reason for this issue to be tracked here.

**Comment by intelliant01** [comment]
@cyberorg Let's make rachel content optional for loading and not part of default install.

**Comment by cyberorg** [comment]
mssupdate serverip rachel
