### ISSUE TITLE
Build offlineweb index.html as per modules needed and module bundle infrastructure

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/offlinewebinfra#6]
_From @cyberorg on March 30, 2017 13:39_

 there is new folder /home/mss/offlineweb/mss/indexer/
Any change to index.html should now go in indexer/htmls/*.html and running ./indexer.sh will create index.html

e.g. to remove kalite
mkdir notneeded
mv htmls/5-kalite.html notneeded/
./indexer.sh

Data folders can be removed if desired:
For kalite:
/home/mssadmin/.kalite and remove kalite autostart from /etc/rc.local
For other content in /srv/www/htdocs/mss/ 
spoken-tutorial
computer-masti
textbooks
rachel
xowa (also needs removing/commenting in /etc/rc.local)

_Copied from original issue: RechercheTech/mss#26_

**Comment by intelliant01** [comment]
Converted to a wiki - ~https://github.com/cyberorg/mss/wiki/Build-offlineweb-index.html-as-per-modules-needed~
https://github.com/RechercheTech/offlinewebinfra/wiki/Build-offlineweb-index.html-as-per-modules-needed

**Comment by intelliant01** [comment]
index.html need not be tracked as it may vary on a per instance basis and can be generated on the fly.

**Comment by intelliant01** [comment]
Updated wiki - https://github.com/RechercheTech/offlinewebinfra/wiki/Build-offlineweb-index.html-as-per-modules-needed with new usage instructions.

**Comment by cyberorg** [comment]
Example bundle xyz needs the following in /home/mss/, see /home/mss/content/* for examples.
xyz.tar (or tar.xz for highly compressible bundle) and xyz (a deployment script)

xyz.tar must contain all the files needed for the bundle in the relative place from / such as 
var/www/html/mss/xyz (folder with actual content including xyz.png used by indexer)
var/www/html/mss/indexer/htmls/80-xyz.html  (number decides where it turns up on index page, artwork used must also be in xyz.tar if not deployed via offlinewebinfra.tar.xz)
lib/systemd/system/xyz.service(systemd service if the service needs auto start on boot)

mkdir -p xyzf/var/www/html/mss/ xyzf/var/www/html/mss/indexer/htmls/ xyzf/lib/systemd/system/
copy all the needed stuff in its correct place in xyzf
cd xyzf && tar cvf ../xyz.tar *

Example deployment script:
#!/bin/bash
CONTENT=xowa
mkdir -p /recovery/offlinewebarchives/
cd /recovery/offlinewebarchives/
wget http://$serverip/mss/$CONTENT.tar
tar xf $CONTENT.tar -C /
cd /var/www/html/mss/indexer/
./indexer.sh
systemctl enable xowa
service xowa start
echo "Xowa setup finished"
